### ISSUE TITLE
Update doesnt work.

### ISSUE THREAD

**Issue by boindil** [TS3Tools/TS3UpdateScript#43] opened 2016-08-26 09:12 UTC
On latest version (5.0.1) the instanceinfo is always wrong and thus the script cant download and update my instance.

It detects 127.0.0.1 as ``SERVERQUERY_IP``, but I got two IPs and teamspeak is running on the secondary only. The script doesnt detect amd64 / linux as well.

**Comment by Sebi94nbg** [comment] 2016-08-26 11:14
Thanks for reporting this problem.

Please replace INSTANCE_PATH with the absolute path to your TS3 instance and execute these commands:

```
# ServerQuery IP
grep -E '^query_ip=' < INSTANCE_PATH/ts3server.ini | cut -d '=' -f 2 | cut -d ',' -f 1

# ServerQuery Port
grep -E '^query_port=[0-9]{4,5}$' < INSTANCE_PATH/ts3server.ini | cut -d '=' -f 2

# Platform: Linux or FreeBSD
grep -Eo '(Linux|FreeBSD)' LATEST_INSTANCE_LOG_FILE

# Architecture: 32bit or 64bit
grep -Eo 'Binary: (64bit|32bit)' LATEST_INSTANCE_LOG_FILE | cut -d " " -f 2
ls $(find ${1} -name 'ts3server_*_*' 2> /dev/null | grep -v 'ts3server_minimal_runscript.sh' | sort | tail -1) | grep -Eo  '(amd64|x86)' | tail -1
```
Have you installed expect and telnet? Which Operating System and version (eg. Debian 8.5) are you using?

**Comment by golimer** [comment] 2016-08-26 15:56
same problem 
# TS3tools TS3UpdateScript Debug Report

Date and time of report: 20160826-1152
TS3UpdateScript Installation Path: /home/ts3
TS3UpdateScript Version: 5.0.1
TS3UpdateScript Parameters: --inform-online-clients --check

## TS3UpdateScript output

Please copy and paste the output of the shell below this line and/or attach a debug file of this script.

## Operating System Details

LSB Version:   	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CentOS
Description:   	CentOS release 6.8 (Final)
Release:       	6.8
Codename:      	Final

Linux server.g3.lt 2.6.32-042stab116.2 #1 SMP Fri Jun 24 15:33:57 MSK 2016 x86_64 x86_64 x86_64 GNU/Linux

### root User locale

LANG=C
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=

### teamspeak User locale

LANG=C
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=

## TS3 Update Details

Update path: 3.0.11.3 -> 3.0.13.3
Instance path: /home/teamspeak
Type Of Files Storage: Local disk
ServerQuery IP: 0.0.0.0
ServerQuery Port: 10011
Installed TS3 Server Version: 3.0.11.3
Installed TS3 Server Build: 1428931591
Installed TS3 Server Platform: linux
TS3 Server Instance Log Path: /home/teamspeak/logs
TS3 Server Architecture: amd64
*nix Owner: teamspeak (UID 500)
*nix Group: teamspeak (GID 500)
Database Type: MariaDB
Update Text (Manually): The server will be updated to the version 3.0.13.3 right now.
Update Text (Cronjob): The server will be updated to version 3.0.13.3 in 5 minutes.
Ignore Clients: 1,
Ignore ServerGroups: 1,2,

## INI Files

### ts3server.ini

machine_id=
default_voice_port=9987
voice_ip=0.0.0.0
liscensepath=
filetransfer_port=30033
filetransfer_ip=0.0.0.0
query_port=10011
query_ip=0.0.0.0
query_ip_whitelist=query_ip_whitelist.txt
query_ip_blacklist=query_ip_blacklist.txt
dbplugin=ts3db_mariadb
dbpluginparameter=ts3db_mariadb.ini
dbsqlpath=sql/
dbsqlcreatepath=create_mariadb/
dblogkeepdays=90
logpath=logs
logquerycommands=0
dbclientkeepdays=30

**Comment by Sebi94nbg** [comment] 2016-08-26 16:13
Perfect!

First of all, you should get a warning message by your TeamSpeak 3 server due of the locale "C". I recommend you, to fix that. You should be able to change this by using the command ``system-config-language``:
```
yum install system-config-language
system-config-language
```

Anyway, I can just see this single problem:
> ServerQuery IP 0.0.0.0 -> Can't be used; should be 127.0.0.1

Everything else looks fine. Please note, that the IP "0.0.0.0" in the ts3server.ini means, that your TS3 server instance is listening on **all** interfaces and IP addresses. If you want, that your server is only listening on a single IP, you have to set this IP there instead of "0.0.0.0".

> It detects 127.0.0.1 as SERVERQUERY_IP, but I got two IPs and teamspeak is running on the secondary only. The script doesnt detect amd64 / linux as well.

Can you please show me your instance details from the output of the script? There should be written "0.0.0.0" as ServerQuery IP and not 127.0.0.1.

Also, as I can see there, the script has detected amd64 and linux in your case. Is that wrong? What should be correct?

**Comment by golimer** [comment] 2016-08-26 16:21
this is VPS centos 6.8 :)
OK changed still same

# TS3tools TS3UpdateScript Debug Report

Date and time of report: 20160826-1219
TS3UpdateScript Installation Path: /home/ts3
TS3UpdateScript Version: 5.0.1
TS3UpdateScript Parameters: --inform-online-clients --check

## TS3UpdateScript output

Please copy and paste the output of the shell below this line and/or attach a debug file of this script.

## Operating System Details

LSB Version:   	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CentOS
Description:   	CentOS release 6.8 (Final)
Release:       	6.8
Codename:      	Final

Linux server.g3.lt 2.6.32-042stab116.2 #1 SMP Fri Jun 24 15:33:57 MSK 2016 x86_64 x86_64 x86_64 GNU/Linux

### root User locale

LANG=C
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=

### teamspeak User locale

LANG=C
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=

## TS3 Update Details

Update path: 3.0.11.3 -> 3.0.13.3
Instance path: /home/teamspeak
Type Of Files Storage: Local disk
ServerQuery IP: 127.0.0.1
ServerQuery Port: 10011
Installed TS3 Server Version: 3.0.11.3
Installed TS3 Server Build: 1428931591
Installed TS3 Server Platform: linux
TS3 Server Instance Log Path: /home/teamspeak/logs
TS3 Server Architecture: amd64
*nix Owner: teamspeak (UID 500)
*nix Group: teamspeak (GID 500)
Database Type: MariaDB
Update Text (Manually): The server will be updated to the version 3.0.13.3 right now.
Update Text (Cronjob): The server will be updated to version 3.0.13.3 in 5 minutes.
Ignore Clients: 1,
Ignore ServerGroups: 1,2,

## INI Files

### ts3server.ini

machine_id=
default_voice_port=9987
voice_ip=0.0.0.0
liscensepath=
filetransfer_port=30033
filetransfer_ip=0.0.0.0
query_port=10011
query_ip=127.0.0.1
query_ip_whitelist=query_ip_whitelist.txt
query_ip_blacklist=query_ip_blacklist.txt
dbplugin=ts3db_mariadb
dbpluginparameter=ts3db_mariadb.ini
dbsqlpath=sql/
dbsqlcreatepath=create_mariadb/
dblogkeepdays=90
logpath=logs
logquerycommands=0
dbclientkeepdays=30

### Database INI-file

[config]
host=127.0.0.1
port=3306
username=golimer
password=CENSORED_PASS
database=ts3db
socket=

## Log files

### Instance Log file

2016-08-26 16:19:37.718914|INFO    |ServerLibPriv |   |TeamSpeak 3 Server 3.0.13.3 (2016-08-18 16:46:43)
2016-08-26 16:19:37.719005|INFO    |ServerLibPriv |   |SystemInformation: Linux 2.6.32-042stab116.2 #1 SMP Fri Jun 24 15:33:57 MSK 2016 x86_64 Binary: 64bit
2016-08-26 16:19:37.719032|WARNING |ServerLibPriv |   |The system locale is set to "C" this can cause unexpected behavior. We advice you to repair your locale!
2016-08-26 16:19:37.720055|INFO    |DatabaseQuery |   |dbPlugin name:    MariaDB plugin, (c)TeamSpeak Systems GmbH
2016-08-26 16:19:37.720101|INFO    |DatabaseQuery |   |dbPlugin version: 1

**Comment by golimer** [comment] 2016-08-26 16:23
Starting to update server manually :(

**Comment by Sebi94nbg** [comment] 2016-08-26 16:33
I'm not very familiar with CentOS, but this article may help you, to change the locale: http://www.cyberciti.biz/faq/how-to-set-locales-i18n-on-a-linux-unix/

You may have already changed it, but need a further command or logout and in again to take effect.

@boindil I believe, you missunderstand something. The ``Installed TS3 Server Platform`` can only be ``linux`` or ``freebsd``. TeamSpeak does only differ between these platforms:
- Windows
- OS X
- Linux
- FreeBSD
You can find this list here: http://teamspeak.com/downloads#server

Due of that, there will never be written "CentOS", "Debian" or anything like that. That's not the TS3 Server Platform, but the operating system distributation. ;)

Now, you've set ``127.0.0.1`` as ServerQuery IP in the ts3server.ini and the TS3 Update Details is also displaying that. So it's using the correct set IP address.

What exactly do you interpret as issue? Just show me the output and let me know, what's wrong with that and I'll help you to fix or get that working. :)

**Comment by golimer** [comment] 2016-08-26 16:39
CENTOS is redhat linux :)

root@server [/home/ts3]# ./TS3UpdateScript --inform-online-clients --check

About: This is the most widely used and fastest shell script to update all your TeamSpeak 3 server instances.
Author: Sebastian Kraetzig <info@ts3-tools.info>
Website: www.ts3-tools.info
facebook: www.facebook.com/TS3Tools
License: GNU GPLv3

 _____ ____ _____       _              _       _        __
|_   _/ ___|___ /      | |_ ___   ___ | |___  (_)_ __  / _| ___
  | | \___ \ |_ \ _____| __/ _ \ / _ \| / __| | | '_ \| |_ / _ \
  | |  ___) |__) |_____| || (_) | (_) | \__ \_| | | | |  _| (_) |
  |_| |____/____/       \__\___/ \___/|_|___(_)_|_| |_|_|  \___/

Script Version: 5.0.1 (2016-08-18)
Script License: Free (limited)

Donate and support this script: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7ZRXLSC2UBVWE

------------------------------------------------------------------

Please wait... Script is working...

Performing self-tests as preventive measures against possible failures                                                                                                                                                              [ OK ]

Collecting necessary information for further tasks                                                                                                                                                                                  [ OK ]

All collected information were validated successfully as preventive measures against possible failures                                                                                                                              [ INFO ]

1 TeamSpeak 3 server instance found...

Collecting as much as possible information for following TeamSpeak 3 server instance: /home/teamspeak
1 instance for update process...
############################################################################
       	Do you want to update this instance to the following version? 3.0.13.3

       	Installation Directory: /home/teamspeak
       	Installed Version: 3.0.11.3 (Build: 1428931591)
       	Installed Platform: Linux
       	Installed Architecture: amd64

       	Instance Log Files: /home/teamspeak/logs
       	Instance TSDNS Binary: /home/teamspeak/tsdns/tsdnsserver_linux_amd64
       	TSDNS Status: Inactive

       	Owner: teamspeak (UID: 500)
       	Group: teamspeak (GID: 500)

       	ServerQuery IP: 127.0.0.1
       	ServerQuery Port: 10011

       	Database Type: MariaDB
############################################################################
Please answer: ([y]es/[n]o) y
Poking clients on following instance: /home/teamspeak                                                                                                                                                                               [ .. ]

send: spawn id exp4 not open
    while executing
"send "clientpoke msg=The\\sserver\\swill\\sbe\\supdated\\sto\\sthe\\sversion\\s3.0.13.3\\sright\\snow. clid=10\r""
                                                                                                                                                                                                                                    [ OK ]

Trying to backup temporary server passwords. Please wait...
Could not backup temporary server passwords. Don't worry. You may just don't had any.
TeamSpeak 3 server instance stopped for update process.
Backup created successful.
TeamSpeak 3 server instance was updated successful.
TeamSpeak 3 server instance was started successful.
Waiting 15 seconds to execute TeamSpeak 3 server and TSDNS health check...
TeamSpeak 3 server is not running any longer.
Due of the failed update, the TS3UpdateScript has created a debug report in /home/teamspeak
Update failed. Rollback to the version '3.0.11.3'.
TeamSpeak 3 server instance was started successful.
Backup was deleted successful.

**Comment by Sebi94nbg** [comment] 2016-08-26 17:39
Thanks for this output.

Can you please send or link the debug file for your update process here? You need to use the parameter ``--debug <file>`` therefore. This will help me, to identify and fix the poking error regarding ``send: spawn id exp4 not open``.

I believe, that you've the same issue like a few other customers. By starting the TS3 server instance it returns a "Segmentation fault" and due of that, the server crashes. I'm already working on a fix for that.

**Comment by golimer** [comment] 2016-08-26 17:55
http://g3.lt/debug.log

P.S. i have change query ip to 0.0.0.0 cause monitor not working not time to search how to fix :)
and i don't think so this is problem :)

**Comment by Sebi94nbg** [comment] 2016-08-26 18:09
Yeah, no problem.

The poking error should be fixed with the issue #45.

Regarding the other issue, I'm currently talking to the TeamSpeak developers. But we think, that we've already found the reason for this cause.

**Comment by golimer** [comment] 2016-08-26 18:11
what you mean "Regarding the other issue,"

**Comment by golimer** [comment] 2016-08-26 18:14
eta of fixing? :) APPROX.

**Comment by boindil** [comment] 2016-08-26 18:18
Hi,
I cant edit the ts3server.ini since I dont use one. All settings are saved in the database (sqlitedb).

The update script detects my instance but cant connect to it, since it thinks the server query port is available on 127.0.0.1 - its not.

I managed to modify the update script to use the correct IP > after that it doesnt know anything about amd64 / linux (which it should since it wanted me to install lsb_release ...)

Anyways, I did update my teamspeak server, but doing so manually would've been faster probably :-D

**Comment by golimer** [comment] 2016-08-26 18:22
I will do same :)

**Comment by Sebi94nbg** [comment] 2016-08-26 18:27
@golimer With "Regarding the other issue" I mean fixing the real cause for the failed update. Should be fixed soon. :)

@boindil So you've just updated the ServerQuery binding IP address within the database? I'm not sure, if that's a supported solution by TeamSpeak. :D 

I'll improve the script, to check the settings in the database too.

What exactly did you change in the TS3UpdateScript? You may have just broken the script with your change. o.O

**Comment by Sebi94nbg** [comment] 2016-08-26 20:33
@boindil Can you provide me some more information, please?

1. What does the ServerQuery command "bindinglist" return for you?
2. Did you set the binding IP for all three types of bindings or only a specific one? If only for a specific one: Please let me know which one.

**Comment by Sebi94nbg** [comment] 2016-08-26 23:18
I've improved the ServerQuery IP detection and fixed the problem with the failed TS3 update process.

**Comment by boindil** [comment] 2016-08-27 13:16
> @boindil So you've just updated the ServerQuery binding IP address within the database? I'm not sure, if that's a supported solution by TeamSpeak. :D
If I'm correct thats the recommended solution .. I've never used a ts3server.ini file. Prior do changing the bindings I had a look at the teamspeak forums.

> What exactly did you change in the TS3UpdateScript? You may have just broken the script with your change. o.O
Yes, I'm pretty sure I did "break" the script. I replaced the important variables (IP, platform, architecture) with static strings. It did update correctly, but that was only a one time change to be able to update. I did revert the script after that.

Still I am not sure, why the script did not detect the platform and architecture using lsb_release (which it asked me to install - error/warning during update)

> What does the ServerQuery command "bindinglist" return for you?
```telnet ts.domain.de 10011
Trying 5.135.X.X...
Connected to ts.domain.de.
Escape character is '^]'.
TS3
Welcome to the TeamSpeak 3 ServerQuery interface, type "help" for a list of commands and "help <command>" for information on a specific command.
login serveradmin mypassword
error id=0 msg=ok
bindinglist
ip=5.135.X.X
error id=0 msg=ok```

> Did you set the binding IP for all three types of bindings or only a specific one? If only for a specific one: Please let me know which one.
I did change all bindings

**Comment by Sebi94nbg** [comment] 2016-08-27 13:22
@boindil lsb_release isn't used to detect the architecture and platform. It's used for debug information, which will be written to the debug report. See @golimer example: https://github.com/TS3Tools/TS3UpdateScript/issues/43#issuecomment-242781602

Thanks for your feedback.

Did you test the latest version of the TS3UpdateScript, if it's displaying the correct server details?

**Comment by boindil** [comment] 2016-08-30 17:52
Hi,
the latest version does display that my server is up2date. Thus it seems everything is working, since the script wasnt able to connect vis server query (now it can connect).

**Comment by Sebi94nbg** [comment] 2016-08-30 17:56
Thanks for your feedback!

**Comment by boindil** [comment] 2016-08-30 17:59
Thank you for your hard work!

**Comment by boindil** [comment] 2016-10-05 16:07
Got to reopen this because I've updated my TS3 server today.

```
Trying to backup temporary server passwords. Please wait...
^CCould not backup temporary server passwords. Don't worry. You may just don't had any.
```

After waiting about 2 minutes, I pressed CTRL+C. The script proceeded after that. I guess it is related to this issue, but I'm not sure.

**Comment by Sebi94nbg** [comment] 2016-10-05 16:32
I don't think, that it's related. Please create a new issue for that and attach, send or provide me a debug file.

By the way: How many virtual servers are running on your instance? It's highly not recommend to use it as ATHP, because it's already taking a few minutes even when there are only 1 to 5 virtual servers.

Here are already to much and old posts about something else. Thanks.

**Closed by Sebi94nbg** 2016-10-05 16:32 UTC
Labels: bug, enhancement
